# Slack
SLACK_TOKEN = "YOUR SLACK'S TOKEN."
USERNAME = "SLACK SENDER'S USERNAME."
CHANNEL = "SLACK CHANNEL'S NAME."
ICON_EMOJI = "SLACK SENDER'S ICON EMOJI."

# Twitter
CONSUMER_KEY = "YOUR TWITTER APP'S KEY."
CONSUMER_SECRET = "YOUR TWITTER APP'S SECRET KEY."
ACCESS_TOKEN = "YOUR TOKEN."
ACCESS_TOKEN_SECRET = "YOUR SECRET TOKEN."

# Destination to save images
SAVE_IMAGE_DIR = './imgs/'
